name:  build-binary

on:
  push:
  #   branches: ['main']
  # pull_request:
  #   branches: ['main']
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  connect:
    runs-on: ubuntu-latest
    steps:
      # Copy repo to action runner
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      # Install Swift and SDK
      - name: Install dependencies
        run: | 
          curl -O https://download.swift.org/swiftly/linux/swiftly-$(uname -m).tar.gz && \
          tar zxf swiftly-$(uname -m).tar.gz && \
          ./swiftly init --quiet-shell-followup && \
          . "${SWIFTLY_HOME_DIR:-$HOME/.local/share/swiftly}/env.sh" && \
          hash -r

          swift sdk install https://download.swift.org/swift-6.2.3-release/static-sdk/swift-6.2.3-RELEASE/swift-6.2.3-RELEASE_static-linux-0.0.1.artifactbundle.tar.gz \
          --checksum f30ec724d824ef43b5546e02ca06a8682dafab4b26a99fbb0e858c347e507a2c

      # Build binary
      - name: Build XS3 Cert Retrieval binary
        working-directory: ${{ github.workspace }}
        run: |
          swift build -c release --experimental-lto-mode=full --swift-sdk aarch64-swift-linux-musl
          echo "Checking aarch64-swift-linux-musl"
          ls -la .build/aarch64-swift-linux-musl/release/xs3-cert

      
      # Build file upload step...
      - name: Upload XS3-Cert binary to Azure Blob Storage 
        uses: azure/cli@9f7ce6f37c31b777ec6c6b6d1dfe7db79f497956
        with:
          inlineScript: |
            az storage blob upload \
            --file ${{ github.workspace }}/.build/aarch64-swift-linux-musl/release/xs3-cert \
            --name xs3-cert-arm64 \
            --blob-url ${{ secrets.AZURE_BLOB_UPLOAD_SAS_URL }}
            --verbose

            echo "Upload successful!"
            az storage blob show   \
            --account-name swdelivery   \
            --container-name xs3-tools   \
            --name xs3-cert-arm64   \
            --query "{Name:name, size: properties.contentLength, lastModified: properties.lastModified, creationTime: properties.creationTime }"   \
            --output table 2>/dev/null

          


        